import "./globals.css";

export const metadata = {
	title: "Next-Kind AI",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="bg-white">{children}</body>
		</html>
	);
}
